// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tp_DWC.Shared.Data;

#nullable disable

namespace Tp_DWC.Shared.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250109183906_GestaoAssistenciasNewBussState")]
    partial class GestaoAssistenciasNewBussState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tp_DWC.Shared.Models.Assistencia", b =>
                {
                    b.Property<int>("NumeroInterno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumeroInterno"));

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPrevisaoEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPrevisaoResolucao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoProblema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("EstadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NumeroInterno");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EstadoId");

                    b.ToTable("Assistencias");
                });

            modelBuilder.Entity("Tp_DWC.Shared.Models.Cliente", b =>
                {
                    b.Property<Guid>("PK_Cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PK_Cliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Tp_DWC.Shared.Models.Contacto", b =>
                {
                    b.Property<Guid>("PK_Contacto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoContacto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PK_Contacto");

                    b.HasIndex("ClienteId");

                    b.ToTable("Contactos");
                });

            modelBuilder.Entity("Tp_DWC.Shared.Models.Email", b =>
                {
                    b.Property<Guid>("PK_Email")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EnderecoEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PK_Email");

                    b.HasIndex("ClienteId");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("Tp_DWC.Shared.Models.EstadoModels.Estado", b =>
                {
                    b.Property<Guid>("PK_Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PK_Estado");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("Tp_DWC.Shared.Models.Morada", b =>
                {
                    b.Property<Guid>("PK_Morada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoradaCompleta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NIF")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("NomeMorada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoMorada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PK_Morada");

                    b.HasIndex("ClienteId");

                    b.ToTable("Moradas");
                });

            modelBuilder.Entity("Tp_DWC.Shared.Models.MudancaEstado", b =>
                {
                    b.Property<Guid>("PK_MudancaEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssistenciaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataMudanca")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EstadoAtualId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NovoEstadoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PK_MudancaEstado");

                    b.HasIndex("AssistenciaId");

                    b.HasIndex("EstadoAtualId");

                    b.HasIndex("NovoEstadoId");

                    b.ToTable("MudancasEstado");
                });

            modelBuilder.Entity("Tp_DWC.Shared.Models.RegistoFotografico", b =>
                {
                    b.Property<Guid>("PK_RegistoFotografico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssistenciaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataRegisto")
                        .HasColumnType("datetime2");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PK_RegistoFotografico");

                    b.HasIndex("AssistenciaId");

                    b.ToTable("RegistoFotograficos");
                });

            modelBuilder.Entity("Tp_DWC.Shared.Models.RegistoMaoDeObra", b =>
                {
                    b.Property<Guid>("PK_RegistoMaoDeObra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssistenciaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataRegisto")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecoTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("QuantidadeHoras")
                        .HasColumnType("int");

                    b.HasKey("PK_RegistoMaoDeObra");

                    b.HasIndex("AssistenciaId");

                    b.ToTable("RegistoMaoDeObras");
                });

            modelBuilder.Entity("Tp_DWC.Shared.Models.RegistoMaterial", b =>
                {
                    b.Property<Guid>("PK_RegistoMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssistenciaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataRegisto")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecoTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("QuantidadeMaterial")
                        .HasColumnType("int");

                    b.HasKey("PK_RegistoMaterial");

                    b.HasIndex("AssistenciaId");

                    b.ToTable("RegistoMaterials");
                });

            modelBuilder.Entity("Tp_DWC.Shared.Models.Assistencia", b =>
                {
                    b.HasOne("Tp_DWC.Shared.Models.Cliente", "Cliente")
                        .WithMany("Assistencias")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tp_DWC.Shared.Models.EstadoModels.Estado", "Estado")
                        .WithMany("Assistencias")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("Tp_DWC.Shared.Models.Contacto", b =>
                {
                    b.HasOne("Tp_DWC.Shared.Models.Cliente", "Cliente")
                        .WithMany("Contactos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Tp_DWC.Shared.Models.Email", b =>
                {
                    b.HasOne("Tp_DWC.Shared.Models.Cliente", "Cliente")
                        .WithMany("Emails")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Tp_DWC.Shared.Models.Morada", b =>
                {
                    b.HasOne("Tp_DWC.Shared.Models.Cliente", "Cliente")
                        .WithMany("Moradas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Tp_DWC.Shared.Models.MudancaEstado", b =>
                {
                    b.HasOne("Tp_DWC.Shared.Models.Assistencia", "Assistencia")
                        .WithMany("MudancasEstado")
                        .HasForeignKey("AssistenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tp_DWC.Shared.Models.EstadoModels.Estado", "EstadoAtual")
                        .WithMany("MudancasEstado")
                        .HasForeignKey("EstadoAtualId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tp_DWC.Shared.Models.EstadoModels.Estado", "NovoEstado")
                        .WithMany()
                        .HasForeignKey("NovoEstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assistencia");

                    b.Navigation("EstadoAtual");

                    b.Navigation("NovoEstado");
                });

            modelBuilder.Entity("Tp_DWC.Shared.Models.RegistoFotografico", b =>
                {
                    b.HasOne("Tp_DWC.Shared.Models.Assistencia", "Assistencia")
                        .WithMany("RegistosFotograficos")
                        .HasForeignKey("AssistenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assistencia");
                });

            modelBuilder.Entity("Tp_DWC.Shared.Models.RegistoMaoDeObra", b =>
                {
                    b.HasOne("Tp_DWC.Shared.Models.Assistencia", "Assistencia")
                        .WithMany("RegistosMaoDeObra")
                        .HasForeignKey("AssistenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assistencia");
                });

            modelBuilder.Entity("Tp_DWC.Shared.Models.RegistoMaterial", b =>
                {
                    b.HasOne("Tp_DWC.Shared.Models.Assistencia", "Assistencia")
                        .WithMany("RegistosMateriais")
                        .HasForeignKey("AssistenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assistencia");
                });

            modelBuilder.Entity("Tp_DWC.Shared.Models.Assistencia", b =>
                {
                    b.Navigation("MudancasEstado");

                    b.Navigation("RegistosFotograficos");

                    b.Navigation("RegistosMaoDeObra");

                    b.Navigation("RegistosMateriais");
                });

            modelBuilder.Entity("Tp_DWC.Shared.Models.Cliente", b =>
                {
                    b.Navigation("Assistencias");

                    b.Navigation("Contactos");

                    b.Navigation("Emails");

                    b.Navigation("Moradas");
                });

            modelBuilder.Entity("Tp_DWC.Shared.Models.EstadoModels.Estado", b =>
                {
                    b.Navigation("Assistencias");

                    b.Navigation("MudancasEstado");
                });
#pragma warning restore 612, 618
        }
    }
}
